/**:
  ros__parameters:
    tracker_ignore_label.UNKNOWN : true
    tracker_ignore_label.CAR : true
    tracker_ignore_label.TRUCK : true
    tracker_ignore_label.BUS : true
    tracker_ignore_label.TRAILER : true
    tracker_ignore_label.MOTORCYCLE : false
    tracker_ignore_label.BICYCLE : false
    tracker_ignore_label.PEDESTRIAN : false
