/**:
  ros__parameters:
    additional_lidars: []
    ransac_input_topics: []

    common_crop_box_filter:
      parameters:
        min_x: -70.0
        max_x: 120.0
        min_y: -75.0
        max_y: 75.0
        margin_max_z: 0.0  # to extend the crop box max_z from vehicle_height
        margin_min_z: -2.5 # to extend the crop box min_z from ground
        negative: False

    common_ground_filter:
      plugin: "ground_segmentation::ScanGroundFilterComponent"
      parameters:
        global_slope_max_angle_deg: 10.0
        local_slope_max_angle_deg: 25.0 # recommended 30.0 for non elevation_grid_mode
        split_points_distance_tolerance: 0.2
        use_virtual_ground_point: True
        split_height_distance: 0.2
        non_ground_height_threshold: 0.20
        grid_size_m: 0.5
        grid_mode_switch_radius: 150.0
        gnd_grid_buffer_size: 5
        detection_range_z_max: 3.2
        elevation_grid_mode: true
        use_recheck_ground_cluster: true
        recheck_start_distance: 20.0
        use_lowest_point: true
        low_priority_region_x: -20.0
        center_pcl_shift: 0.0
        radial_divider_angle_deg: 1.0
        # debug parameters
        publish_processing_time_detail: false

    # common_ground_filter:
    #   plugin: "ground_segmentation::RayGroundFilterComponent"
    #   parameters:
    #     general_max_slope: 10.0
    #     local_max_slope: 10.0
    #     min_height_threshold: 0.2

    front_upper_crop_box_filter:
      parameters:
        min_x: -50.0
        max_x: 100.0
        min_y: -50.0
        max_y: 50.0
        margin_max_z: 0.0  # to extend the crop box max_z from vehicle_height
        margin_min_z: -2.5 # to extend the crop box min_z from ground
        negative: False

    front_upper_ground_filter:
      plugin: "ground_segmentation::ScanGroundFilterComponent"
      parameters:
        global_slope_max_angle_deg: 10.0
        local_slope_max_angle_deg: 18.0 # recommended 30.0 for non elevation_grid_mode
        split_points_distance_tolerance: 0.20  # recommended 0.045 for non elevation_grid_mode
        split_height_distance: 0.2 # recommended 0.15 for non elevation_grid_mode
        use_virtual_ground_point: False
        non_ground_height_threshold: 0.1
        grid_size_m: 0.1
        grid_mode_switch_radius: 20.0
        gnd_grid_buffer_size: 4
        detection_range_z_max: 3.2
        elevation_grid_mode: true
        use_recheck_ground_cluster: true
        use_lowest_point: true
        low_priority_region_x: -20.0
        center_pcl_shift: 0.0
        radial_divider_angle_deg: 1.0
        # debug parameters
        publish_processing_time_detail: false

    front_lower_crop_box_filter:
      parameters:
        min_x: -50.0
        max_x: 100.0
        min_y: -50.0
        max_y: 50.0
        margin_max_z: 0.0  # to extend the crop box max_z from vehicle_height
        margin_min_z: -2.5 # to extend the crop box min_z from ground
        negative: False

    front_lower_ground_filter:
      plugin: "ground_segmentation::ScanGroundFilterComponent"
      parameters:
        global_slope_max_angle_deg: 10.0
        local_slope_max_angle_deg: 18.0 # recommended 30.0 for non elevation_grid_mode
        split_points_distance_tolerance: 0.20 # recommended 0.1 for non elevation_grid_mode
        split_height_distance: 0.2      # recommended 0.05 for non elevation_grid_mode
        use_virtual_ground_point: False
        non_ground_height_threshold: 0.1
        grid_size_m: 0.1
        grid_mode_switch_radius: 20.0
        gnd_grid_buffer_size: 4
        detection_range_z_max: 3.2
        elevation_grid_mode: false
        use_recheck_ground_cluster: false
        use_lowest_point: true
        low_priority_region_x: -20.0
        center_pcl_shift: 0.0
        radial_divider_angle_deg: 1.0
        # debug parameters
        publish_processing_time_detail: false
